version: '3'

tasks:
  build:
    cmds:
      - uv run maturin develop

  test:
    deps: [build]
    cmds:
      - uv run pytest tests/

  stub:
    cmds:
      - cargo run --bin stub_gen

  version:
    cmds:
      - cargo set-version {{.CLI_ARGS}}
